Update to Ansible 2.2 to workaround a bug in debops.ifupdown rewrite
TASK [debops.ifupdown/env : debug] *********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: {{ lookup("template", "lookup/ifupdown__combined_interfaces.j2") | from_yaml }}: 'dict' object has no attribute 'read'
fatal: [testing.template]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}